function QAMatrix = DataQA(QAVector,ObsPrWin)

% This function gets as input vector of numbers 0 2-6 and gives it back as
% a matrix of 48 half hours by 6 coulumns. The number in each column is
% indicating the origin of the nans in the half hour.
% in column 1 the overall number of nans in the current half hour window.
% in column 2 the number of nans generated by diagnostics
% in column 3 the number of nans that were under the min
% in column 4 the number of nans that were over the max
% in column 5 the number of nans that the DeSpike detected
% in column 6 the number of nans that were originaly in the window.

if mod(length(QAVector),ObsPrWin)==0
    QAMat=reshape(QAVector, ObsPrWin, length(QAVector)/ObsPrWin);
    QAMatrix=histc(QAMat,1:6)';
    QAMatrix(:,1)=sum(QAMatrix(:,2:6),2);
else
    disp('problem with QAVector')
end

end

